apiVersion: trustyai.opendatahub.io/v1alpha1
kind: NemoGuardrails
metadata:
  name: nemoguardrails
  namespace: llm
  annotations:
    security.opendatahub.io/enable-auth: 'true'
spec:
  nemoConfigs:
    - name: guardrail-openai
      configMaps:
        - guardrail-openai
      default: true
    - name: guardrail-qwen
      configMaps:
        - guardrail-qwen
  env:
    - name: "OPENAI_API_KEY"
      valueFrom:
        secretKeyRef:
          name: "openai-guardrail-config"
          key: "openai-api-key"
